language: bash
dist: bionic
services:
  - docker
branches:
  only:
  - master
  - production
  - /(feature/).*/
  - /(hotfix/).*/
  - /(fix/).*/
  - destroy
before_install:
  - sh ./ci/tools/terraform/install.sh 0.12.21
jobs:
  include:
    - stage: quality_check
      # MAKE SURE THE CODE IS WELL WRITTEN AND PASS TESTS
      script: ./ci/scripts/jobs/quality_check.sh
      if: 'type IN (pull_request)'
      
    - stage: formation_check
      # MAKE SURE FORMATION SCRIPTS ARE VALID AND WELLFORMED/FORMATED
      script: ./ci/scripts/jobs/formation_check.sh
      if: 'type IN (pull_request) and branch =~ /^(master|production)$/'

    - stage: img_push
      script: ./ci/scripts/jobs/image_push.sh
      if: 'type IN (push) and branch =~ /^(master|production)$/'

    - stage: stg_plan
      script: ./ci/scripts/jobs/staging_plan.sh
      if: 'branch =~ /^(master|production)$/'

    - stage: STG_APPLY
      script: ./ci/scripts/jobs/staging_apply.sh
      if: 'branch =~ /^(master|production)$/'

    - stage: PRD_PLAN
      script: ./ci/scripts/jobs/production_plan.sh
      if: 'branch == "production"'

    - stage: PRD_APPLY
      script: ./ci/scripts/jobs/production_apply.sh
      if: 'branch == "production"'

    - stage: DESTROY
      script: ./ci/scripts/jobs/destroy.sh
      if: 'branch == "destroy"'