
language: bash
sudo: required
services:
  - docker
branches:
  only:
  - master
  - production
  - /(feature/).*/
  - /(hotfix/).*/
  - /(fix/).*/
env:
  - MXMD_FORMATION_VERSION=0.12.21
before_install:
  - cd ./ci/init && sudo formation.sh
jobs:
  include:
    - stage: QUALITY_CHECK
      # MAKE SURE THE CODE IS WELL WRITTEN AND PASS TESTS
      script: ./ci/sh/jobs/quality_check.sh
      # if: 'type IN (pull_request)'
    - stage: FORMATION_CHECK
      # MAKE SURE FORMATION SCRIPTS ARE VALID AND WELLFORMED/FORMATED
      script: ./ci/sh/jobs/formation_check.sh
      # if: 'type IN (pull_request) and branch =~ /^(master|production)$/'
    - stage: IMG_PUSH
      script: ./ci/sh/jobs/image_push.sh
      if: 'type IN (push) and branch =~ /^(master|production)$/'
    - stage: STG_PLAN
      script: ./ci/sh/jobs/staging_plan.sh
      if: 'branch =~ /^(master|production)$/'
    - stage: STG_APPLY
      script: ./ci/sh/jobs/staging_apply.sh
      if: 'branch =~ /^(master|production)$/'
    - stage: PRD_PLAN
      script: ./ci/sh/jobs/production_plan.sh
      if: 'branch == "production"'
    - stage: PRD_APPLY
      script: ./ci/sh/jobs/production_apply.sh
      if: 'branch == "production"'
    - stage: DESTROY
      script: ./ci/sh/jobs/destroy.sh
      if: 'branch == "production"'