language: generic
sudo: required
services:
  - docker

jobs:
  include:
    - stage: QUALITY_CHECK
      script: ./ci/sh/jobs/quality_check.sh
      if: '(branch =~ /^(feature|hotfix|fix)/.*/ && $TRAVIS_PULL_REQUEST == "true") || branch =~ /^(master|production)$/'
    - stage: IMG_PUSH
      script: ./ci/sh/jobs/image_push.sh
      if: '(branch =~ /^(feature|hotfix|fix)/.*/ && $TRAVIS_PULL_REQUEST == "true") || branch =~ /^(master|production)$/'
    - stage: STG_PLAN
      script: ./ci/sh/jobs/staging_plan.sh
      if: 'branch =~ /^(master|production)$/'
    - stage: STG_APPLY
      script: ./ci/sh/jobs/staging_apply.sh
      if: 'branch =~ /^(master|production)$/'
    - stage: PRD_PLAN
      script: ./ci/sh/jobs/production_plan.sh
      if: 'branch == "production"'
    - stage: PRD_APPLY
      script: ./ci/sh/jobs/production_apply.sh
      if: 'branch == "production"'
    - stage: DESTROY
      script: ./ci/sh/jobs/destroy.sh
      if: 'branch == "production"'