FROM node:alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY ./package.json ./
RUN yarn global add @angular/cli
RUN yarn global add @angular-devkit/build-angular 
RUN yarn install
RUN ng config --global cli.packageManager yarn

# add app
COPY . .

# start app
# CMD ng serve --hots 0.0.0.0 --port 2000