version: '3.3'

services:
  client:
    stdin_open: true
    environment:
      - LISTEN_PORT=8000
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - "8000:8000"
    volumes: 
      # In this line I'm telling docker-compose
      # to use the node_modules folder INSIDE the
      # container instead of trying to map the folder
      # in my local machine, mainly because it might
      # not be present locally and the one inside the
      # container should be the prefered source of 
      # truth about these dependencies.
      - /app/node_modules
      # As for everything else, make sure to reference
      # the local source code so I can get live reloading
      # for source code that is being changed locally.
      - ./client:/app
  server:
    environment:
      - APP_PORT=9000
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - "9000:9000"
    volumes: 
      # In this line I'm telling docker-compose
      # to use the node_modules folder INSIDE the
      # container instead of trying to map the folder
      # in my local machine, mainly because it might
      # not be present locally and the one inside the
      # container should be the prefered source of 
      # truth about these dependencies.
      - /app/node_modules
      # As for everything else, make sure to reference
      # the local source code so I can get live reloading
      # for source code that is being changed locally.
      - ./server:/app