FROM node:alpine

# set working directory
WORKDIR /app
# copy only the dependencies
# installation blueprint
COPY package.json ./
# download and install dependencies
# in a node_modules folder of its own
RUN yarn install
# copy everything else now 
# that node_modules has been 
# generated inside the container 
COPY . ./
# since this is not hosted by nginx
# just yet, use yarn to start serving
# the application with live updates
CMD ["yarn", "start"]