version: '3.3'
services:
  terraform:
    image: hashicorp/terraform:0.12.21
    working_dir: /infra
    volumes:
      - .:/infra
      - ./../awscf/roles:/roles
      - ./../awscf/policies:/policies
      - ./../../scripts/init:/scripts
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}